### ISSUE TITLE
Can't instantiate abstract class OpenAIAgent with abstract method supported_languages

### ISSUE THREAD

**Issue by gavinpbennett** [joselcaguilar/azure-openai-ha#27]
I have updated to 2023.5.0, and appear to be having issues getting this integration to start. I had it installed (but not tested) with the prior version 2023.4.6, then removed and thought I would wait for 5.0.  My system is setup in New Zealand. 
Below is the log entry info:
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/azure_openai_conversation/__init__.py:53
Integration: Azure OpenAI Conversation (documentation, issues)
First occurred: 09:57:32 (1 occurrences)
Last logged: 09:57:32

Error setting up entry Azure OpenAI Conversation for azure_openai_conversation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/azure_openai_conversation/__init__.py", line 53, in async_setup_entry
    conversation.async_set_agent(hass, entry, OpenAIAgent(hass, entry))
TypeError: Can't instantiate abstract class OpenAIAgent with abstract method supported_languages

**Comment by joselcaguilar** [comment]
Hi @gavinpbennett, yes it's a known issue, they introduced some breaking changes for custom assistants in HA 2023.5.0 (released yesterday). I'll add support for that version asap, no ETA 😊

**Comment by joselcaguilar** [comment]
Support for **HA 2023.5.x** has been added in the latest major [v1.0.0](https://github.com/joselcaguilar/azure-openai-ha/releases/tag/v1.0.0), please follow the [instructions for HA 2023.5.x users](https://github.com/joselcaguilar/azure-openai-ha/#home-assistant-20235x-users) and take a look to the [supported versions](https://github.com/joselcaguilar/azure-openai-ha/#limitations).

Enjoy @gavinpbennett, the support of this development is appreciated 😊

**Comment by gavinpbennett** [comment]
@joselcaguilar Thanks for the good work.
