### ISSUE TITLE
Is there some way of storing the response in e.g an attribute?

### ISSUE THREAD

**Issue by wigster** [joselcaguilar/azure-openai-ha#28]
Hi,

I would like to have HA read the ChatGPT responses through TTS using a media player. Is that possible somehow, e.g. to write the response to an attribute of an entity, where there isn't a 250 character limit.

**Comment by joselcaguilar** [comment]
Hi @wigster, you have the possibility to check the response from Home Assistant [Logger](https://www.home-assistant.io/integrations/logger/) 🙂

**Comment by wigster** [comment]
Do you know off hand of some way of ingesting a log into HA so it can be handled as data?

**Comment by joselcaguilar** [comment]
> Do you know off hand of some way of ingesting a log into HA so it can be handled as data?

@wigster The integration uses [logger](https://www.home-assistant.io/integrations/logger/), so you can retrieve the responses from there, with that said, maybe there's another easier option with **HA 2023.5.0** and [v1.0.0](https://github.com/joselcaguilar/azure-openai-ha/releases/tag/v1.0.0) release + your desired TTS:

![image](https://user-images.githubusercontent.com/7523585/236224241-fb92002a-ac34-469c-803f-4257c5af83e5.png)

**Comment by joselcaguilar** [comment]
I'm going to close this issue once the recommendations have been provided @wigster, please feel free to re-open the issue if needed 😊
